#!/usr/bin/env bash


make

sudo cp ./spark /usr/local/bin/spark


# remove old first
sed -i '/# spark start/,/# spark end/d' ~/.bashrc

# install new entry in bashrc
echo '
# spark start

function _update_spark_prompt()
{
    PS1=$(spark $?)
}

export PROMPT_COMMAND="_update_spark_prompt"

# spark end
' >> ~/.bashrc

