#!/usr/bin/env bash


make

sudo install -D -m 755 ./spark /usr/local/bin/spark

# sudo install -D -m 755 ./sptheme /usr/local/bin/sptheme

# install -D -m 644 ~/.spark/themes


# remove old first
sed -i '/# spark start/,/# spark end/d' ~/.bashrc

# install new entry in bashrc
echo '
# spark start

function _update_spark_prompt()
{
    PS1=$(spark $?)
}

export PROMPT_COMMAND="_update_spark_prompt"

# spark end
' >> ~/.bashrc

