#!/usr/bin/env bash


make || exit 1

install -D -m 755 -T ./spark ~/.spark/spark

# remove old first
sed -i '/# spark start/,/# spark end/d' ~/.bashrc

# install new entry in bashrc
echo '
# spark start

alias spark=~/.spark/spark

function _update_spark_prompt()
{
    PS1=$(spark $?)
}

export PROMPT_COMMAND="_update_spark_prompt"

# spark end
' >> ~/.bashrc

