#!/usr/bin/env bash




# PS1='\[\033[01;32m\]\u\[\033[02;37m\]@\h\[\033[00m\]:\[\033[01;34m\]`shorten \w`\[\033[00m\]\$ '



# ---------------------------------------------------------------------- #
#                          FRANTISEK PROMPT
# ---------------------------------------------------------------------- #


function shorten()
{
    dir="$1"
    hom=$(echo "$HOME" | sed -e 's$/$\\/$g')
    dir=$(echo "$dir" | sed "s/$hom/~/")
    if [ ${#dir} -gt 40 ]; then
        echo …`echo ${dir:$((${#dir} - 40)):${#dir}}`
    else
        echo $dir
    fi
}

function retval_color()
{
    ret="$1"
    if [ "$ret" -eq 0 ];
    then
        echo -e "\033[48;2;0;91;187m"
    else
        echo -e "\033[41m"
    fi
}

function retval()
{
    ret="$1"
    if [ "$ret" -eq 0 ];
    then
        echo " ✓"
    else
        echo " ⨯"
    fi
}

function pp_host()
{
    name="$1"
    # echo -e "\033[1;43m"
    printf '\033[48;2;0;91;187m\033[38;2;255;255;255m'
}

function export_retval()
{
    ret="$?"
    export RET_COLOR=$(retval_color $ret)
    export RET_SYMBOL=$(retval $ret)
    export USR_COLOR=$(printf '\033[48;2;165;165;165m\033[38;2;0;0;0m')
    # export HOST_COLOR=$(printf '\033[48;2;0;91;187m')
    export PWD_COLOR=$(printf '\033[48;2;165;165;165m\033[38;2;0;0;0m')
}

export PROMPT_COMMAND='export_retval'
export PS1="\[\$RET_COLOR\]\$RET_SYMBOL "'\[$USR_COLOR\] \u \[\033[02;37m\]\[$(pp_host \h)\] \h \[\033[00m\]\[$PWD_COLOR\] $(shorten \w) \[\033[00m\] '

# ---------------------------------------------------------------------- #





