#!/bin/sh

set -ex

[ -z "$CXX" ] && CXX=clang++
[ -z "$CLANG_TIDY" ] && CLANG_TIDY=clang-tidy

echo; make clean; SANITIZE=undefined CXX=$CXX make all test/test_spark -j && test/test_spark && ./spark -e
echo; make clean; SANITIZE=address   CXX=$CXX make all test/test_spark -j && test/test_spark && ./spark -e
# echo; make clean; SANITIZE=memory    CXX=$CXX make all test/test_spark -j && test/test_spark && ./spark -e
# echo; make clean; SANITIZE=dataflow  CXX=$CXX make all test/test_spark -j && test/test_spark && ./spark -e

make clean; CXXFLAGS="-std=c++20 -pedantic -Wall -Wextra -O2 -g" make all test/test_spark -j
valgrind --error-exitcode=200 ./spark -e
valgrind --error-exitcode=200 test/test_spark

CLANG_TIDY=$CLANG_TIDY make clang-tidy
