name: Clang-Tidy
run-name: Running clang-tidy for push by ${{ github.actor }}
on: [push]

jobs:
  run-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Clang-Tidy
        run: make clang-tidy
