name: Valgrind
run-name: Running valgrind for push by ${{ github.actor }}
on: [push]

jobs:
  run-valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build
        run: CXXFLAGS="-std=c++20 -pedantic -Wall -Wextra -O2 -g" make clean all test/test_spark

      - name: Valgrind spark
        run: valgrind ./spark -e

      - name: Valgrind test
        run: valgrind test/test_spark
